fix: do not fail silently on type constraint error in your variant file
For example variant has been failing silently on `type = "string"` (this needs to be `type = string`). This fixes that. The error message would now look like:

```
Error: Invalid type specification
  on example/test.variant line 3, in option "namespace":
   3:   type = "string"
A type specification is either a primitive type keyword (bool, number, string) or a complex type
constructor call, like list(string).
```