fix: run should not panic when a step is missing `run` block
It will now produce the following message on missing `run` block within a `step` block:

```
Error: Missing run block

  on issue5/test.variant line 43, in job "terraform init all":
  43:   step "init" {

A run block is required.

```

Fixes #5